add test for paypalmestype
Rindula/hirsch pull request #779
Opened 2022-03-15 09:56 UTC by Killaxy

2022-03-15 10:00 UTC, Rindula requested changes
Bitte auch negativtests

2022-03-15 10:02 UTC, Killaxy commented
> Bitte auch negativtests

gibt aber keine required Felder dementsprechend keine negativtests

2022-03-15 10:03 UTC, Rindula commented
> > Bitte auch negativtests
> 
> gibt aber keine required Felder dementsprechend keine negativtests

Dann validation einfügen 😉

2022-03-21 15:21 UTC, Rindula approved these changes

2022-03-21 15:27 UTC, merged